### The evaluate package makes it easy to capture all the outputs (results, text, messages, warnings, errors, and plots) from an expression. Create a function like capture_it() that also captures the warnings and errors generated by a function.

#TODO: When I have internet access and can research the evaluate package

capture_it <- function(default = NULL, f, quiet = FALSE) {
  force(f)
  function(...) {
    out <- default
    tryCatch(out <- f(...)
             , error = function(e)
             ,  warning = function(w) 
             ,  message = function(m) 
             )
    out
  }
}
